# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: P2B Gamification
email: daniel.vergeylen@place2be.biz
description: > # this means to ignore newlines until "baseurl:"
  Gamification Schemes made easy. Combine simple to complex mechanics to create gamified loyalty programs at large scales.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://doc.place2be.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: place2bebiz
github_username:  dvergeylen

# Build settings
markdown: kramdown
highlighter: rouge

# Theme: keep minima theme and override defaults
# See minima tree structure here: https://jekyllrb.com/docs/themes/#overriding-theme-defaults
theme: minima
permalink: pretty

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - src
